### ISSUE TITLE
PHP 8?

### ISSUE THREAD

**Issue by wu-edward** [richardbporter/drush-users-commands#45]
The php constraint in composer.json is set to "php": "^7.4". Is there anything blocking PHP 8 compatibility?

**Comment by richardbporter** [comment]
Not that I know of but I haven't tested it out yet. I can give it a shot when I have time.

**Comment by richardbporter** [comment]
I changed the constrain in #55.

**Comment by wu-edward** [comment]
Great, thanks!

@jprasmussen ^
